<?xml version="1.0" ?>
<robot name= "tao" xmlns:xacro="http://www.ros.org.wiki/xacro">

 	<xacro:include filename="$(find tao_description)/urdf/tao_properties.xacro" /> 
 	<xacro:include filename="$(find tao_description)/urdf/tao_chassis.xacro" /> 
 	<xacro:include filename="$(find tao_description)/urdf/tao_wheel.xacro" /> 
 	<xacro:include filename="$(find tao_description)/urdf/tao_castor.xacro" />

<!-- 
 	<xacro:Bodyy nameb="${BASE2}"
		namel="${LINK21}" r="1" g="1" b="0" a="1" ox="0" oy="0" oz="0.215"/> -->

	<xacro:chassis
		r="1" g="0.2" b="1" a="1"
		parentt="base_footprint2" childd="base_link2"/>
	
	<xacro:wheel 
 		name="left2"
 		translation="
 			0 
 			${WHEEL_SEPARATION/2} 
 			${WHEEL_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}"
 		rotation="0 0 0"
 		parent="base_link2"/> 

 	<xacro:wheel 
 		name="right2"
 		translation="
 			0 
 			${-WHEEL_SEPARATION/2} 
 			${WHEEL_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}"
 		rotation="0 0 0"
 		parent="base_link2"/> 

 	<xacro:castor 
 		name="right_front2"
 		translation="
 			${CASTOR_SEPARATION_X/2} 
 			${CASTOR_SEPARATION_Y/2} 
 			${CASTOR_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}"
 		rotation="0 0 0"
 		parent="base_link2"/> 

 	<xacro:castor 
 		name="left_front2"
 		translation="
 			${CASTOR_SEPARATION_X/2} 
 			${-CASTOR_SEPARATION_Y/2} 
 			${CASTOR_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}"
 		rotation="0 0 0"
 		parent="base_link2"/> 
 	<xacro:castor 
 		name="right_rear2"
 		translation="
 			${-CASTOR_SEPARATION_X/2} 
 			${CASTOR_SEPARATION_Y/2} 
 			${CASTOR_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}"
 		rotation="0 0 0"
 		parent="base_link2"/> 
 	<xacro:castor 
 		name="left_rear2"
 		translation="
 			${-CASTOR_SEPARATION_X/2} 
 			${-CASTOR_SEPARATION_Y/2} 
 			${CASTOR_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}"
 		rotation="0 0 0"
 		parent="base_link2"/>



</robot>